### ISSUE TITLE
line style in flow

### ISSUE THREAD

**Issue by bertrandmartel** [adrai/flowchart.js#113]
I needed to generate a flowchart that would emphasize the path taken by each element. To do this I needed to update the style of each lines dynamically. So I've forked and modified a bit your library to implement a new separator `@>` to define the flow with each of the specific svg style in json format : 

```
st@>op1({"stroke":"Red"})@>cond1({"stroke":"Red","stroke-width":6,"arrow-end":"classic-wide-long"})@>cond6({"stroke":"Red"})@>op4({"stroke":"Red"})@>end({"stroke":"Red"})
```
The idea is to override the line style attribute depending on the destination symbol key with a `lineStyle` object that define a list of style to apply to symbols (with symbol key as field) 

For `st` symbol (from the example above)
```
lineStyle = {
    "op1" : {
         "stroke":"Red"
   }
}
```
Example of result 
![linestyle](https://user-images.githubusercontent.com/5183022/29744899-7bc48784-8aae-11e7-94e8-b7e79d17100d.png)

I've opted to get the line style to be directly parsed in the flowchart format because I didn't manage to get it work with css class. I found [this](https://stackoverflow.com/questions/4522967/how-to-add-a-css-class-to-a-raphael-object) but it didn't worked for line style (also it seems it won't work everywhere with css class)

What do you think about this approach ? Could this be a relevant PR ?

**Comment by adrai** [comment]
ok, so if I understand it correctly finally you have to "normally" define the chart

```
...
st->op1->cond1(no)->cond6(yes)->op4->end
...
```

and afterwards additionally define your styled path, right?
```
st@>op1({"stroke":"Red"})@>cond1({"stroke":"Red","stroke-width":6,"arrow-end":"classic-wide-long"})@>cond6({"stroke":"Red"})@>op4({"stroke":"Red"})@>end({"stroke":"Red"})
```

**Comment by bertrandmartel** [comment]
@adrai Yes that's it, are you ok with that syntax ?

**Comment by adrai** [comment]
all fine
