### ISSUE TITLE
what is the badge of js.org for?

### ISSUE THREAD

**Issue by xuyuji9000** [adrai/flowchart.js#118]
I thought it was a chatroom, but it jump to js.org website which don't contain chat feature, then I'm kinda confused. 

![screen shot 2017-08-29 at 9 47 45 pm](https://user-images.githubusercontent.com/4877346/29824338-e3d25f3e-8d03-11e7-919f-88f550da4916.png)

Can anybody enlighten me on this?

**Comment by adrai** [comment]
https://dns.js.org/

**Comment by xuyuji9000** [comment]
Understood. Thanks man.
