### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by ngzhongcai** [adrai/flowchart.js#124]
![screen shot 2017-11-23 at 14 48 11](https://user-images.githubusercontent.com/1439419/33161353-067bd55e-d05e-11e7-9893-7e4c12a7338e.png)
Thank you for the library. I'm generating the screenshot flowchart. Like to seek on how to trim that whitespace on the right.

**Comment by adrai** [comment]
Can you provide an example?
i.e. with https://jsfiddle.net/ or similar

**Comment by ngzhongcai** [comment]
https://jsfiddle.net/wvpnjz0b/1

**Comment by ngzhongcai** [comment]
or is there a way to center the flowchart?

**Comment by ngzhongcai** [comment]
I reset the viewbox to svg.getBbox()
