### ISSUE TITLE
In Conditional allow for 'true' or 'false' along with 'yes' and 'no'

### ISSUE THREAD

**Issue by bhedge** [adrai/flowchart.js#126]
It would be nice to have the Conditional be able to evaluate 'true' or 'false'.  Would be willing to provide a PR if there is enough interest in this change.

Thank you!

**Comment by adrai** [comment]
Good idea. Feel free to provide a PR...

**Comment by bhedge** [comment]
I need to pull the code and validate this but thought I would ask.  It looks like there is a configuration item to allow for alternate 'yes' and 'no' text.  Could this allow for mapping these items to 'true' and 'false' like this?
`'yes-text': 'true',
'no-text': 'false'`

**Comment by adrai** [comment]
yes, but this is only the display text...
I thiught you wanted it in the flow syntax...

**Comment by bhedge** [comment]
Yes, will submit a PR for the flow syntax then and if the user wants to override the display text, they can use the configuration items provided.

**Comment by adrai** [comment]
👍

**Comment by bhedge** [comment]
Created PR https://github.com/adrai/flowchart.js/pull/128

Let me know if I need to submit this in a different way or make any changes.  Thanks!
