### ISSUE TITLE
how can i draw branches

### ISSUE THREAD

**Issue by shangxinbo** [adrai/flowchart.js#130]
```
st=>start: portal
op1=>operation: auth
op2=>operation: trade
e=>end

st->op1->e
st->op2->e
```
look at my code. I want to draw two branches(op1 & op2) from st and to end. how do i do?

**Comment by hilvarenbeek** [comment]
I think that is currently not possible, except if you use a condition to make the split path:

```
st=>start: portal
split=>condition: split
op1=>operation: auth
op2=>operation: trade
e=>end

st->split
split(yes)->op1->e
split(no)->op2->e
```

**Comment by adrai** [comment]
there is a new parallel component... can you try it?
