### ISSUE TITLE
How to create clickable arrows/connectors

### ISSUE THREAD

**Issue by ronaldpaul** [adrai/flowchart.js#131]
I would like to generate a dynamic flowchart based on JSON data and I want the arrows that connect two elements to be made clickable so that some information can be displayed in a popup window. Moreover, is it possible to generate large amount of dynamic connectors, new dynamic elements and multiple connections from the same element using this library?

**Comment by adrai** [comment]
no

**Comment by hilvarenbeek** [comment]
What do you mean by dynamic? Flowchart.js creates an SVG e.g. inside a DIV, and you can clear the DIV's content and re-render the chart e.g. document.getElementById(target).innerHTML="";  [...] diagram.drawSVG(target, options);

The only way to split the path right now, is to add a Condition, and it only takes 'yes' or 'no' (two paths), although you can change the yes-text and no-text in options. 

There is no way to specify a HTML link for an arrow, only for an element (e.g. an operation).
