### ISSUE TITLE
Cant Seem To Get Any Result, Even From Example

### ISSUE THREAD

**Issue by NJseo** [adrai/flowchart.js#135]
Cant Seem To Get Any Result, Even From Example

https://www.smartychat.co/flowchart/

https://www.smartychat.co/flowchart/example/index.html

**Comment by adrai** [comment]
for http://www.smartychat.co/flowchart/example/index.html you serve the html page from https and want to load http scripts this is not allowed... try without https (only http)

and for the other url
just see in your devtools console there is written:

> GET http://www.smartychat.co/flowchart/raphael-min.js 404 (Not Found)

**Comment by NJseo** [comment]
LOL... sometime brilliance escapes me
