### ISSUE TITLE
Parallel operation

### ISSUE THREAD

**Issue by NRajkumar** [adrai/flowchart.js#139]
How to create a parallel operation flow chart. i.e one operation to two different operations, then that two operations to one operation.

**Comment by canDry** [comment]
BUMP!

Yes, I'd like to know how to do this too.

**Comment by adrai** [comment]
not possible right now...

Feel free to submit a PR if possible.

**Comment by adrai** [comment]
there is s new parallel component... can you try if that works for your use case?

**Comment by ankitjain1990** [comment]
Hi @adrai 

I have tried the parallel component but still, I am not able to draw flowchart for below statements

> st=>start: Start|past
> e=>end: End|past
> op3=>parallel: Stuff1|current
> op1=>parallel: My Operation|current
> op2=>parallel: Stuff|current
> sub1=>subroutine: My Subroutine|current
> sub2=>subroutine: My Subroutine1|current
> sub3=>subroutine: My op2|current
> sub4=>subroutine: My op22|current
> 
> st(right)->op1
> 
> op1(path1, bottom)->sub1->sub2
> op1(path2, right)->op2
> 
> op2(path3, bottom)->sub3->sub4
> op2(path4, right)->op3
> 
> op3(path5, right)->e

I have attached the output image below  
![output](https://user-images.githubusercontent.com/20102923/44711842-eeb9bb80-aacc-11e8-8faa-805b31b1f53e.PNG)
 
but I want below output 
![output](https://user-images.githubusercontent.com/20102923/44712038-80c1c400-aacd-11e8-879a-d5cedd05de90.PNG)

please guide me for same

**Comment by adrai** [comment]
There is only path1, path2 and path3 (no path4 or 5)
try:

```

st=>start: Start|past
e=>end: End|past
op3=>parallel: Stuff1|current
op1=>parallel: My Operation|current
op2=>parallel: Stuff|current
sub1=>subroutine: My Subroutine|current
sub2=>subroutine: My Subroutine1|current
sub3=>subroutine: My op2|current
sub4=>subroutine: My op22|current

st(right)->op1

op1(path1, bottom)->sub1->sub2
op1(path2, right)->op2

op2(path1, bottom)->sub3->sub4
op2(path2, right)->op3

op3(path2, right)->e
```

**Comment by ankitjain1990** [comment]
Thanks @adrai for your help
