### ISSUE TITLE
Implemented the new feature, to create a parallel operations

### ISSUE THREAD

**Issue by sudhakar-sekar** [adrai/flowchart.js#144]
Hi @adrai,

I have implemented the new feature. Added new type called "parallel" similar to the current "operations".
Using parallel type, we are able to connect one source[of type parallel] to multiple targets. I implemented to allow three connections from parallel.

In condition, we already have 'yes' or 'no'. In parallel, I have implemented 'path1', 'path2' and 'path3'.

Please find the below snippet,
```
Start=>start: Start\n
da=>parallel: da\n
da1=>operation: da1\n
da2=>operation: da2\n
da3=>operation: da3\n
da4=>operation: da4\n
da5=>operation: da5\n
da6=>operation: da6\n
End=>end: End\n

Start(right)->da\n
da(path1, right)->da1\n
da(path2, bottom)->da2\n
da(path3, top)->da3\n
da1(right)->da4\n
da2(right)->da5\n
da3(right)->da6\n
da4(right)->End\n
da5(right)->End\n
da6(right)->End\n
```
Please find the below attached screenshot,
![image](https://user-images.githubusercontent.com/29774378/38540512-cb6247b4-3cb9-11e8-9d63-68297280f671.png)

Let me know so that I can create a PR with flowchart.symbol.parallel.js.

Thanks,
Sudhakar

**Comment by adrai** [comment]
cool idea...
Feel free to go ahead...

**Comment by sudhakar-sekar** [comment]
Hi @adrai,
I have cloned these repository and made all the changes.
I am created a new branch and commit the changes using,
   git commit -m "" -> command.
Then, I am trying to push the commit, when I am hitting the push commit,
git push origin Feature_Parallel_Operations
fatal: HttpRequestException encountered.
  ```
 An error occurred while sending the request.
Username for 'https://github.com': sudhakar120693@gmail.com
remote: Permission to adrai/flowchart.js.git denied to sudhakar-sekar.
fatal: unable to access 'https://github.com/adrai/flowchart.js.git/': The reques                                                                                                                                  ted URL returned error: 403
```
I got the above error. i am not able to push my changes. Please give permission to push my changes.

Thanks,
Sudhakar

**Comment by adrai** [comment]
Create a Pull Request directly on github: https://yangsu.github.io/pull-request-tutorial/

**Comment by sudhakar-sekar** [comment]
@adrai ,
Created a PR. Please take a look at it.
https://github.com/adrai/flowchart.js/pull/145

Thanks,
Sudhakar.

**Comment by adrai** [comment]
v1.11.0
