### ISSUE TITLE
Send line behind the parallel symbols

### ISSUE THREAD

**Issue by amrithany** [adrai/flowchart.js#150]
hi, how do I send my line behind my parallel symbols? At present, the line is on top of the symbol. Please see attached file.

![lines behind symbols](https://user-images.githubusercontent.com/10050489/39943343-858a0bde-5530-11e8-8c32-a7390a0e95f7.PNG)

Here's the code

st->cond                                                                                                                                                                                                     
cond(yes, right)->para
para(path1, bottom)->opa->op3
para(path2, top)->op3

Thanks!

**Comment by adrai** [comment]
Can you paste the full example?

**Comment by amrithany** [comment]
Thank you. Works perfectly.
