### ISSUE TITLE
How do I get the parallel lines to the left

### ISSUE THREAD

**Issue by touxing** [adrai/flowchart.js#152]
Hi adrai，
    I had a problem. I want the parallel lines to the left, but only to the right or to the bottom.
![snipaste_2018-06-02_14-03-13](https://user-images.githubusercontent.com/16403653/40871453-ad28c258-666e-11e8-8617-1bf4b145c26e.png)

**Comment by touxing** [comment]
st=>start: start
e=>end: end
op1=>operation: 1.1
op2=>parallel: 2
op2_1_1=>operation: 2.1.1
op2_1_2=>operation: 2.1.2
op2_2_1=>operation: 2.2.1
op2_2_2=>operation: 2.2.2
op3=>operation: 3
op4=>parallel: 4
op4_1_1=>operation: 4.1.1
op4_1_2=>operation: 4.1.2
op4_2_1=>operation: 4.2.1
op4_2_2=>operation: 4.2.2
op4_3_1=>operation: 4.3.1

st->op1->op2

op2(path1, bottom)->op2_1_1->op2_1_2->op3
op2(path2, right)->op2_2_1->op2_2_2->op3

op3->op4

op4(path1, bottom)->op4_1_1->op4_1_2->e
op4(path2, right)->op4_2_1->op4_2_2->e
op4(path3, left)->op4_3_1->e  //it's something wrong

**Comment by adrai** [comment]
with v1.11.2 it should be a bit better

**Comment by touxing** [comment]
thinks，so cool

**Comment by touxing** [comment]
thinks， It's just what I wanted.
