### ISSUE TITLE
Am I using the parallel tasks correctly?

### ISSUE THREAD

**Issue by simkimsia** [adrai/flowchart.js#154]
![image](https://user-images.githubusercontent.com/245021/41340663-7f6a0fd8-6f2a-11e8-823f-101d323b4c0b.png)
I am using quite a fair bit of parallel tasks and I noticed that they don't line up together.

My purposes of having those IO or subroutine is because they further elaborate what's happening at the individual processes.

Am I using parallel tasks correctly?

My code
```
st=>start
            e=>end
            vendor_submit=>parallel: Vendor Submit Files
            files=>inputoutput: 1 Excel per quotation
            1 PDF per quotation
            1 Excel as summary
            identify_type=>operation: PSS1 identify ASP/3PP/RES 
            check_completeness=>parallel: PSS1 check for completeness
            data_submitted=>inputoutput: quote no.
            quote value
            project
            enter_quotation_data=>parallel: PSS1 enter quotation data
            and assign PSS2
            notify_vendor=>subroutine: email notification to vendor
            breakdown_persite=>parallel: PSS2 breakdown per site
            breakdown_data_submitted=>inputoutput: Quotation Excel
            Quotation PDF
            Summary Excel

            st->vendor_submit
            vendor_submit(path1, right)->files
            vendor_submit(path2, bottom)->identify_type
            identify_type->check_completeness
            check_completeness(path1, right)->data_submitted
            check_completeness(path2, bottom)->enter_quotation_data
            enter_quotation_data(path1, right)->notify_vendor
            enter_quotation_data(path2, bottom)->breakdown_persite
            breakdown_persite(path1, right)->breakdown_data_submitted
            breakdown_persite(path2, bottom)->e
```

**Comment by adrai** [comment]
I think so... how should the graph look like?

**Comment by simkimsia** [comment]
I was hoping to have the nodes on the right handside to be vertically aligned. Is that possible?

 Because as I add more and more nodes on the main branch, and each node on the main branch will have parallel tasks I extend to the right, the entire diagram will likely grow wider.

**Comment by adrai** [comment]
no, this is not possible right now :-(

**Comment by simkimsia** [comment]
okay understood. thanks for answering. U want me to close this ticket?

**Comment by simkimsia** [comment]
Oh I just realised that the answer to what I need is

`check_completeness(align-next=no)=>parallel: PSS1 check for completeness`

So with that I will close this ticket
