### ISSUE TITLE
More compact horizontal rendering

### ISSUE THREAD

**Issue by stof** [adrai/flowchart.js#155]
When chaining lots of condition, the right branch of them gets pushed further and further for top ones (any time we add a new one at the bottom).

While this may be useful when needing to have a bottom branch from them to avoid overlap, it makes the graph a lot less readable when the node on the right is an end node.

See  this flowchart for an example:

```
st=>start: Start
e=>end: ...
d=>end: button-dangerous-action
c=>end: button-creation
conf=>end: button-confirmation
prim=>end: button-primary-action
del_cond=>condition: Delete button?
crea_cond=>condition: Creation button?
conf_cond=>condition: confirmation button?
prim_cond=>condition: primary action?

st->del_cond
del_cond(yes, right)->d
del_cond(no)->crea_cond
crea_cond(no)->conf_cond
crea_cond(yes, right)->c
conf_cond(yes, right)->conf
conf_cond(no)->prim_cond
prim_cond(yes, right)->prim
prim_cond(no)->e
```

I don't know enough the library to be able to implement this myself.

**Comment by adrai** [comment]
... this is not possible right now... but I have an idea... as soon as I have a couple of minutes I will try something...

**Comment by adrai** [comment]
Can you try with v1.11.3 ?

**Comment by stof** [comment]
Yeah, looks much better.
