### ISSUE TITLE
left vs. right

### ISSUE THREAD

**Issue by gmarquart** [adrai/flowchart.js#156]
I really like the idea of being able to make flowcharts via code and was hoping to throw some in some html5 presentations -- so thanks for your work!  however, i ran into a couple issues...

I was trying to make a flowchart that snakes back and forth and while the behavior of op#(right) seems relatively predictable, when I do the similar to the left (i.e., op#(left)), the length of the resulting arrow seems to depend on the position?

code:
`st=>start: start
e=>end: end
op1=>operation: 1
op2=>operation: 2
op3=>operation: 3
op4=>operation: 4
op5=>operation: 5
op6=>operation: 6
op7=>operation: 7
op8=>operation: 8
op9=>operation: 9
op10=>operation: 10
op11=>operation: 11
op12=>operation: 12
op13=>operation: 13
op14=>operation: 14
op15=>operation: 15
st->op1(right)->op2(right)->op3(right)->op4->op5(left)->op6->op7(right)->op8(right)->op9(right)->op10->op11(left)->op12(right)->op13->op14(left)->op15->e`

result:
![left-v-right](https://user-images.githubusercontent.com/10225805/42762444-ae9ad788-8910-11e8-8855-2088fa55709f.png)

any advice would be greatly appreciated!

**Comment by adrai** [comment]
not possible with the current algorithm :-(

**Comment by gmarquart** [comment]
):  thanks for the quick reply!

**Comment by 63byeongchan** [comment]
ㅠ...I am also having the same issue.  i need that algorithm... i want that algorithm....
