### ISSUE TITLE
How to add the style "cursor:pointer" to the element <a> ?

### ISSUE THREAD

**Issue by Andersonfeng** [adrai/flowchart.js#158]
Example:
![tim 20180723105835](https://user-images.githubusercontent.com/13361365/43055115-5bd7a632-8e67-11e8-8530-25f4821421b2.png)

**Comment by Andersonfeng** [comment]
I wonder is there any way  to do this without modifying js or css?

**Comment by ChiragSSinghal** [comment]
You can try replacing the link with "#" or with "#[blank]" (for new tab) for implementing the "cursor:pointer" without changing js or css.

```
st=>start: Start:>#[blank]
e=>end:>#
```
![20180821_142742](https://user-images.githubusercontent.com/37487664/44421697-5319cf80-a54f-11e8-883d-ddee0ae1c5b6.jpg)
![20180821_142736](https://user-images.githubusercontent.com/37487664/44421698-5319cf80-a54f-11e8-9148-b0fa757b08b8.jpg)
