### ISSUE TITLE
decisions

### ISSUE THREAD

**Issue by brunocarc** [adrai/flowchart.js#169]
Hello Adrai
I tried to get no actions after 2 decisions below each other. Without success. Could you give me an advice?

thanks / regards
Bruno
![flowchart-decision-no-above-each-other](https://user-images.githubusercontent.com/48520554/54283916-4b7b5000-459f-11e9-8061-85db8dd26614.png)

**Comment by adrai** [comment]
Ciao Bruno!
Was meinst du genau?

**Comment by brunocarc** [comment]
Hallo Adriano

Danke fürs schnelle Antworten. Wir möchten das Plug-in für die Generierung von Prozessdokumenten verwenden. Hier spreizt die Graphik so, dass die rechte Spalte betroffen ist.

Wir suchen hier eine Möglichkeit, die zwei Klärungsschritte übereinander darzustellen, sodass es nur zwei Spalten sind.

[cid:image002.jpg@01D4D9BD.42A23500]


Merci fürs Prüfen

--

Bruno Carcer

058 200 66 03
Infofactory AG | Badstrasse 50 | 5200 Brugg

www.infofactory.ch<http://www.infofactory.ch>
www.modulpark.ch<http://www.modulpark.ch>



Von: Adriano Raiano <notifications@github.com>
Gesendet: Mittwoch, 13. März 2019 15:55
An: adrai/flowchart.js <flowchart.js@noreply.github.com>
Cc: Bruno Carcer <bruno.carcer@infofactory.ch>; Author <author@noreply.github.com>
Betreff: Re: [adrai/flowchart.js] decisions (#169)


Ciao Bruno!
Was meinst du genau?

**Comment by adrai** [comment]
vielleicht hilft `cond(align-next=no)`

**Comment by brunocarc** [comment]
Guten Morgen

In der Tat, das hat geholfen. Danke. Kann man irgendwo eine Donation machen bei dir?

[cid:image003.jpg@01D4DB05.1E7599D0]

liebe Grüsse

--

Bruno Carcer

058 200 66 03
Infofactory AG | Badstrasse 50 | 5200 Brugg

www.infofactory.ch<http://www.infofactory.ch>
www.modulpark.ch<http://www.modulpark.ch>



Von: Adriano Raiano <notifications@github.com>
Gesendet: Mittwoch, 13. März 2019 20:25
An: adrai/flowchart.js <flowchart.js@noreply.github.com>
Cc: Bruno Carcer <bruno.carcer@infofactory.ch>; Author <author@noreply.github.com>
Betreff: Re: [adrai/flowchart.js] decisions (#169)


vielleicht hilft cond(align-next=no)

**Comment by adrai** [comment]
Gut zu hören.

Eine Donation direkt machen kann man nicht, aber indirekt, wenn man https://github.com/i18next/i18next oder locize.com kennt kann man es ein wenig populärer machen, indem man ein Tweet oder Post macht ;-)

Gruss
Adriano
