### ISSUE TITLE
Firefox drag and drop redirect into nowhere

### ISSUE THREAD

**Issue by LockiStrike** [adrai/flowchart.js#170]
Hi
Our team faced with issue that when you try to connect one connector into nothing (to any place on the page where no other object or edges) it redirects you to `about:blank` url in Firefox.
Please could you provide us a way how to prevent it because as I know there is no way to add any logic to drag events callbacks.
![case](https://user-images.githubusercontent.com/22641574/56289689-30fe3e80-612a-11e9-9349-5182ae48cc84.gif)

Reproduces only in Firefox on any OS.
Thank you in advance.

**Comment by adrai** [comment]
Are you sure this relates to this library?
I've never seen this UI.

**Comment by LockiStrike** [comment]
I'm so sorry, we have dependency `ngFlowChart` and I was pretty sure that this is just angular implementation of your library but it looks like not.
Sorry
