### ISSUE TITLE
Yes direction left

### ISSUE THREAD

**Issue by g3blv** [adrai/flowchart.js#182]
I have this code

```
st=>start: Start
op1=>operation: Check if item exists
cond1=>condition: Item exists?
op2=>operation: Set ID
op3=>operation: Create item and set ID
e=>end

st->op1->cond1
cond1(yes, left)->op2->e
cond1(no, right)->op3->e
```
I've created this Fiddle -> http://jsfiddle.net/vecyrh5u
The Fiddle is using:
`http://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.0/raphael-min.js`
`http://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.2/jquery.min.js`
`http://flowchart.js.org/flowchart-latest.js`

For `cond1` I would the like to make the **Yes** alternative to point left. Is that possible?

**Comment by adrai** [comment]
not possible with the current algorithm... https://github.com/adrai/flowchart.js/issues/15#issuecomment-37029886
