### ISSUE TITLE
flowchart designed json response 

### ISSUE THREAD

**Issue by Madhava446** [adrai/flowchart.js#196]
![image](https://user-images.githubusercontent.com/13332510/73833807-972a8e00-4830-11ea-8c92-c4c33dadc2e7.png)

1. I've designed a workflow using flowchart.js How can I get its response. 
2. Can I get events for start/stop clicks..

**Comment by adrai** [comment]
Sorry, I don’t understand

**Comment by Madhava446** [comment]
> Sorry, I don’t understand

**Comment by Madhava446** [comment]
I've designed the above workflow using drag and drop from left side controls.
Can I get the response(json) of the designed work flow?
My requirement is to save the workflow in db. 
I've some additional requirements as well. Considering start/Task/End as buttons in the above designed workflow, I want click events of the buttons.
Can you please help in implementing these features?
Thanks!

**Comment by adrai** [comment]
I’ve never seen this UI 🤷‍♂️
flowchart.js uses a text representation to generate a chart like here: http://flowchart.js.org

**Comment by Madhava446** [comment]
https://github.com/visionfortech/Draw-flowchart-with-drag-and-drop-in-HTML-and-JavaScript
From the above source, I've downloaded and ran the html file
![image](https://user-images.githubusercontent.com/13332510/73839792-d959cc80-483c-11ea-902e-59c0d500c4cf.png)

I get this. Can you please take this reference

**Comment by adrai** [comment]
Sorry, looks like this is not the same library.
Try to create an issue here: https://github.com/visionfortech/Draw-flowchart-with-drag-and-drop-in-HTML-and-JavaScript/issues

**Comment by Madhava446** [comment]
Sorry to trouble you Adrai
Thanks
