### ISSUE TITLE
How exactly to start using it for Readme?

### ISSUE THREAD

**Issue by satyajituk** [adrai/flowchart.js#197]
I am absolute beginner in this. Can someone tell me what exact step I need to take to generate flow diagrams in my readme in my project? 
Of course just copying the example doesn't work. 
Thanks

**Comment by adrai** [comment]
Create it here: https://flowchart.js.org/
And save the image of the flowchart, then add that image to the readme

**Comment by satyajituk** [comment]
Thanks @adrai 
I actually wanted to have the image's boxes clickable which open links. Just like how your Readme is doing. How can I do that?

**Comment by adrai** [comment]
In which readme? In this (https://github.com/adrai/flowchart.js/blob/master/README.md) readme it's just a svg image

**Comment by satyajituk** [comment]
Yes I meant that readme. Ok. If I right click I see no option to save as svg image or something? Is there any other way to save the image as a vector file in https://flowchart.js.org/ ?

**Comment by adrai** [comment]
copy that svg element
![image](https://user-images.githubusercontent.com/1086194/74037462-99baee00-49be-11ea-9e7e-fc014b6e1ef6.png)

**Comment by satyajituk** [comment]
That works! Thanks! 
It comes out to be a huge chunk of text though. I assume that's normal right? 
Thanks for the help!

**Comment by adrai** [comment]
Yes, this is an svg...

**Comment by satyajituk** [comment]
So I copied and saved as `file.svg`
Then in my readme I did: `![Alt text](file.svg)`
I can see the image now in readme but it is not clickable the way I expected. If I click it simply opens the file.svg and that itself doesn't seem clickable at various boxes. 
Did I do something wrong?

**Comment by adrai** [comment]
How did you configured the link?

st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com

without blank it should work (at least it works in my readme)

**Comment by satyajituk** [comment]
What I meant to say that  in https://flowchart.js.org/ you can actually click on `start` and it opens `google.com` in a new tab. This functionality seems to be missing with including svg in readme. It is same for your readme as well as my readme. 

Because when I click even on your readme, I dont go to `google.com` but rather the svg opens in another tab.

**Comment by adrai** [comment]
Yes, I can confirm this. But I don’t know why.
But if I click on “End” it works 🤷‍♂️

On 10 Feb 2020, at 11:51, satyajituk <notifications@github.com> wrote:

﻿

What I meant to say that in https://flowchart.js.org/ you can actually click on start and it opens google.com in a new tab. This functionality seems to be missing with including svg in readme. It is same for your readme as well as my readme.

Because when I click even on your readme, I dont go to google.com but rather the svg opens in another tab.

**Comment by satyajituk** [comment]
Oh, for me none works. Not even `End`. No matter where I click, it only opens the svg in another tab. Are you saying if you click on `End` on your Readme then it works? 
I will try with different browser to try luck. Now I am using Chrome.

**Comment by adrai** [comment]
Oh no... it is not working either... sorry for the confusion.

**Comment by satyajituk** [comment]
The only workaround solution I found is to rightclick on the svg shown in readme and select `open image in new tab`. 
After it opens in the new tab, then it is clickable individually as we expect. 
So it is some issue of github and its readme not being able to show an svg properly.

Another way can be just to have a raster format of the image which links to the link when it opens in a new tab so that when a user simply clicks on the image the "correct" vector format opens. 

Let me know if you have any more innovative idea. And thanks for responding so quickly to my queries! :)

**Comment by satyajituk** [comment]
Is it possible to include a small image in the condition or any boxes? Or only texts are possible? Thanks!

**Comment by adrai** [comment]
only text
