### ISSUE TITLE
Making the Size of the Rectangle Constant..

### ISSUE THREAD

**Issue by ChiradeepNanabala** [adrai/flowchart.js#200]
Hello, 

Can anyone please help me to make the rectangle size(Operation) constant irrespective of the text size present inside that...

Thanks in advance...

**Comment by adrai** [comment]
This is currently not possible.

**Comment by ChiradeepNanabala** [comment]
So, Can't we fix the length and width of the rectangle?

**Comment by adrai** [comment]
No, but feel free to create a PR.

**Comment by ChiradeepNanabala** [comment]
okay, Thank you
