### ISSUE TITLE
Flow Chart not generated properly in first attempt

### ISSUE THREAD

**Issue by ateefansari06** [adrai/flowchart.js#201]
![ImproperFlowchart](https://user-images.githubusercontent.com/26874513/75233336-b2a90900-57de-11ea-8bfa-1ac8abc27f9d.PNG)
It Appears like this after First attempt,
Then appears properly in next attempts.
![ProperFlowchart](https://user-images.githubusercontent.com/26874513/75233483-f3a11d80-57de-11ea-9f1b-d6afa11d8266.PNG)

**Comment by ateefansari06** [comment]
@adrai I would like to know why this occurs and how to resolve this issue.
Please assist me.

**Comment by adrai** [comment]
Have no idea... you need to debug

**Comment by ateefansari06** [comment]
I checked it, I think the issue was in the first attempt, the div was hidden before flowchart was made so SVG was unable to give proper size to the elements.
After I made the div visible before the first render, it was able to draw the flowchart properly.
