### ISSUE TITLE
Fehler Chartdarstellung

### ISSUE THREAD

**Issue by brunocarc** [adrai/flowchart.js#207]
Hallo Adriano
wir können ein Darstellungsproblem deiner Chart Funktion nicht lösen. Eventuell weisst du Abhilfe. 
Der Entwickler hat schon versucht, es über die Richtung des Sprungziels zu beeinflussen. Aber konnte es nicht lösen. Es scheint, dass die Sprungziele nicht ansprechbar sind. 

![Fehler-Chartlinie](https://user-images.githubusercontent.com/48520554/87141365-3dc50000-c2a3-11ea-95df-1952016d74b7.jpg)

**Comment by adrai** [comment]
Vielleicht die 07 (Ja, Nein) Richtung ändern? Ja (rechts), Nein (unten)?
