### ISSUE TITLE
Q: How to change the color for all lines in one go? 

### ISSUE THREAD

**Issue by vic-t** [adrai/flowchart.js#220]
First of all, thanks for making this tool. 

I wish to use flowchart.js on a site using a dark template. This means that black connector lines are hardly visible. I understand I can change the color for strokes between containers on a per connection basis as demonstrated in the third demo on the official website. But is there a way to just set a color for all connector lines at once?

**Comment by adrai** [comment]
just set the appropriate color in the options: `'line-color': 'white'`

example: https://github.com/adrai/flowchart.js/blob/master/example/index.html#L40
