### ISSUE TITLE
Is it possible to keep elements in one column?

### ISSUE THREAD

**Issue by vic-t** [adrai/flowchart.js#221]
I wanted to try to make a diagram for a case statement, similar to 

![image](https://user-images.githubusercontent.com/13408858/118290812-22d0a700-b4d7-11eb-8f9c-7663ebd14054.png)

When trying to replicate this in Flowchart.js, the three statement blocks are not held in one vertical column but drift apart quite substantially. 

![image](https://user-images.githubusercontent.com/13408858/118290952-4e539180-b4d7-11eb-98c8-54db8dd6b450.png)

I assume there's not much I can do about this, right?

**Comment by adrai** [comment]
no, it works like this

**Comment by vic-t** [comment]
As described in the PR https://github.com/adrai/flowchart.js/issues/115, using the flag `align-next=no`, it does actually seem possible to do what I asked. 

Here's the code: 

```
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
c1(align-next=no)=>condition: Condition 1
c2(align-next=no)=>condition: Condition 2
c3(align-next=no)=>condition: Condition 3
c4(align-next=no)=>condition: Default
op1=>operation: Operation 1
op2=>operation: Operation 2
op3=>operation: Operation 3
op4=>operation: Default
op5=>operation: End Statement

st->c1(no,bottom)->c2(no,bottom)->c3(no,bottom)->c4(yes,right)->op4(right)->op5(right)->e
c1(yes,right)->op1(right)->op5->e
c2(yes,right)->op2(right)->op5->e
c3(yes,right)->op3(right)->op5->e
```

And here's the result: 

![grafik](https://user-images.githubusercontent.com/13408858/119328275-383a9380-bc84-11eb-822c-6805f63cf9e5.png)

Not exactly sure why the lines going away from op2 and op3 don't remain horizontal but that's a minor nuisance.
