### ISSUE TITLE
is condition with 3 and more options possible?

### ISSUE THREAD

**Issue by gomedya** [adrai/flowchart.js#225]
examples are given for yes/no but i want to add a "maybe" and i could not. is it possible? thanks.

**Comment by adrai** [comment]
not with condition, but with parallel

**Comment by gomedya** [comment]
maybe i miss your point , could you give me an example for yes/no/maybe with parallels?

**Comment by adrai** [comment]
feel free to submit a PR... just saying ;-)

**Comment by gomedya** [comment]
deep down you know what i say is true and it serves to improve this fantastic tool , ball is at your court

PS. i don't know what PR is
