### ISSUE TITLE
dark mode for http://flowchart.js.org/?

### ISSUE THREAD

**Issue by PatternFinder** [adrai/flowchart.js#232]
possible to work a dark mode to http://flowchart.js.org/ ? under win10 dark mode/chrome, http://flowchart.js.org/ is completely unreadable with both background and fonts being white

**Comment by adrai** [comment]
You can define your custom colors and styles: https://github.com/adrai/flowchart.js/blob/master/example/index.html#L42
if you want a built-in dark mode detection etc... feel free to provide a PR

**Comment by PatternFinder** [comment]
thanks for the follow up.
