### ISSUE TITLE
How can I create below structure?

### ISSUE THREAD

**Issue by SudhirFaurecia** [adrai/flowchart.js#234]
Hello,
How can we create below structure. Please note I am not creating parallel operation. I don't want a node(line) between Operation 2a and operation 2b. I want node from operation 1 to operation 2a and operation 2b.

operation1=>operation: operation1
operation2a=>operation: operation1 2a
operation2b=>operation: operation 2b
operation3=>operation: operation3

![image](https://user-images.githubusercontent.com/108078183/175761898-d300ddb4-759b-484e-b5f6-7c4a1249ab17.png)

**Comment by adrai** [comment]
Not sure I understood, but if you need an operation to have 2 branches, you need to use parallel. There's no other way.

```
st=>start
e=>end
op1=>parallel: Operation 1
op2a=>operation: Operation 2a
op2b=>operation: Operation 2b
op3=>operation: Operation 3

st->op1
op1(path1, left)->op2a->op3
op1(path2)->op2b->op3
op3->e
```

<img width="457" alt="image" src="https://user-images.githubusercontent.com/1086194/175764295-e87ba7c3-c376-402e-9ca7-b87f91f5cfa0.png">

**Comment by SudhirFaurecia** [comment]
If we consider hierarchy, operation 2a and operation 2b should be between operation 1 and operation 3(on separate line).

**Comment by adrai** [comment]
Not possible
