### ISSUE TITLE
[Question] How to make two nodes output to the same node?

### ISSUE THREAD

**Issue by Rullec** [adrai/flowchart.js#235]
Hi all,
    Thanks for this excellenet library!
    I cannot figure out how to make two nodes output to another node together. Consider:
```flow
st1=>start: first
st2=>start: second
op=>operation: handle
e=>end: end

st1->op
st2->op
op->end
```

But it doesn't work.

Can you help me with this question? Thanks!

**Comment by adrai** [comment]
You can't have multiple starts...

try something like:

```
st=>start: start
p=>parallel: parallel
o1=>operation: first
o2=>operation: second
op=>operation: handle
e=>end: end

st->p
p(path1, left)->o1->op
p(path2, right)->o2->op
op->e
```

**Comment by Rullec** [comment]
> st=>start: start
> p=>parallel: parallel
> o1=>operation: first
> o2=>operation: second
> op=>operation: handle
> e=>end: end
> 
> st->p
> p(path1, left)->o1->op
> p(path2, right)->o2->op
> op->e

Oh, I see. Thanks for this solution! 
I think maybe the lib `flowchart.js` just focus on literally `flowchart` instead of a general-purpose chart? In another word, `flowchart` have and only have one beginning?

**Comment by adrai** [comment]
yes
