### ISSUE TITLE
Left path not working in parallel.

### ISSUE THREAD

**Issue by SudhirFaurecia** [adrai/flowchart.js#237]
Hello 
I have 3 paths from a parallel task as below.
```
st=>start: START
start=>parallel: -_-
end=>end: END
ldm=>operation: Leather Defect Marking
spreadcncroll=>operation: Spreading rolls and CNC cutting roll material
scannest=>operation: Leather scanning and nesting /CNC cutting real leather
spreadcncfoam=>operation: Spreading rolls and CNC cutting foam / spacer material
laminfoambacking=>operation: 2D lamination with foam backing
foaminject=>operation: Foam injection
finecutleather=>operation: Fine cutting leather
leathersplit=>operation: Leather splitting
subsurtreat=>operation: Substrate surface treatment

st->start(path1, left)->spreadcncroll->spreadcncfoam->finecutleather->embroidery->embossing->sewing->mixingwaterglue
mixingwaterglue(path1, left)->tapewelding->end
mixingwaterglue(path2, right)->cooling->end
start(path2, bottom)->ldm->scannest->leathersplit->finecutleather->embroidery->embossing->sewing
start(path3, right)->subsurtreat->placingcutfoam->end

```
In the image below you can see left path is not going to left. It is overlapping each other on right side only.
![image](https://user-images.githubusercontent.com/108078183/182780316-90227be3-bdb7-4804-a400-2f2c76e955a8.png)

Could you please support.
Thank you.

**Comment by adrai** [comment]
answered here: https://github.com/adrai/flowchart.js/issues/236#issuecomment-1204837645

**Comment by adrai** [comment]
btw: flowchart.js will display "nicer" charts only for simple flows...

**Comment by SudhirFaurecia** [comment]
#236 is not applicable in this case as in parallel task only I mentioned it should go to left like this - `start(path1, left)->spreadcncroll` but is is obverlapping
