### ISSUE TITLE
Open modal popup when clicked on node.

### ISSUE THREAD

**Issue by SudhirFaurecia** [adrai/flowchart.js#238]
How can we open different modal(bootstrap) popups for every node we click.
ex : If we click on "leather defect marking" it should open an modal popup containing image (with some links) which explains leather defect marking process. same if we click on "Foam Injection" it should open an modal popup containing image (with some links) which explains foam injection process. 

See image.
![image](https://user-images.githubusercontent.com/108078183/185060500-b78a5b23-d646-4121-84de-6f2e10c77229.png)

**Comment by adrai** [comment]
you can define links, like: `st=>start: Start:>http://www.google.com[blank]`

So just define a link containing some sort of identifier for your own page that shows up your modal...
i.e. `http://localhost:8080/modal?component=start`
