### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by SudhirFaurecia** [adrai/flowchart.js#239]
I have added links in flowchart. see image below-
![image](https://user-images.githubusercontent.com/108078183/188386177-12256c61-57cb-4630-bbe1-39ebe5512c1d.png)

It is generating flowchart successfully and also showing link when I hover on it.
![image](https://user-images.githubusercontent.com/108078183/188387005-f58f3e74-4c3c-4a53-89cf-c09245f90e3b.png)

But issue here is when I click the box it is not opening the link(www.google.com).
I checked in browser I see below errors.
![image](https://user-images.githubusercontent.com/108078183/188388728-0b088fa0-3d97-42c3-87ca-64d3186fce56.png)

Is it because of this (raphael)error link is not working?
How to make the link work. 
Thank you https://github.com/adrai

**Comment by adrai** [comment]
please create areproducible example... seems to work here: https://flowchart.js.org/

**Comment by SudhirFaurecia** [comment]
I am not sure why it is not working at my side. Is there any way we can connect on call and while sharing screen you an check the code.?

**Comment by SudhirFaurecia** [comment]
Minimal reproducible example:::

Step 1: Declaration
                    st=>start: START
                    start=>parallel: -_-
                    end=>end: END:>http://www.yahoo.com
                    ldm=>operation: Leather Defect Marking
                    spreadcncroll=>operation: Spreading rolls and CNC cutting roll material
                    scannest=>operation: Leather scanning and nesting /CNC cutting real leather
                    spreadcncfoam=>operation: Spreading rolls and CNC cutting foam / spacer material

Step 2: Implementation
                  st->start(path1, bottom)->end 
                  start(path3, right)->end 
Problem : If you notice, I have added link to 'end' but it is not working. I am not able to click on it.

Let me know if you need more details. I should have uploaded image but my employer does not allow me.

**Comment by adrai** [comment]
Seems to work here: https://flowchart.js.org/

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1086194/225573809-fe3a9da7-d73a-43eb-a93b-03a2ff5d0452.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/1086194/225573979-4b09c619-531e-493b-b98f-b8ada7c7f1ce.png">


So must be something in your website/code... sorry
