### ISSUE TITLE
Igor?

### ISSUE THREAD

**Issue by diadz** [adrai/flowchart.js#240]
Any plans to make flowchart.js compatible with Igor? I tried to upgrade my Dokuwiki instance and the flowcharts wouldn't render when running under Igor. I've rolled back for now and everything is working again, but would like to upgrade eventually.

**Comment by adrai** [comment]
What is Igor?

**Comment by diadz** [comment]
> What is Igor?

Sorry, I shouldn't have assumed you would know. It is the latest release of Dokuwiki from July 2022.

**Comment by adrai** [comment]
Sorry, I'm not familiar with it... 🤷‍♂️

**Comment by diadz** [comment]
Now I see, it is another project that built a flowchart.js extension for Dokuwiki. Makes sense you aren't familiar with it, (and wouldn't be doing anything to fix my issue.)

https://github.com/ghbore/flowchartjs
