### ISSUE TITLE
how to use this in typescript?

### ISSUE THREAD

**Issue by liwei478** [adrai/flowchart.js#247]
Nowdays, i plan to use in vue3, typescript, vite, but when i install the flowchart, it tips me to install the type, so i install the type package, but the error occurs:
![image](https://github.com/adrai/flowchart.js/assets/56572769/ecaa328a-d10b-4a2c-b5f4-ab80b4d4d1cd)
and my dependencies are as follows:
![image](https://github.com/adrai/flowchart.js/assets/56572769/8f7ea5ae-72a9-4ba1-886e-ca74fdef090a)
how can solve this problem? Or need i to use other chart libraries?

**Comment by adrai** [comment]
flowchart.js has no types and since TypeScript is a superset of JavaScript, there should be no problem

**Comment by wirekang** [comment]
@liwei478 You installed wrong package: install `flowchart.js` instead of `flowchart`.

**Comment by wirekang** [comment]
@adrai Looks like you forgot that somebody added types for this awesome project(4 years ago 👍🏼).
https://github.com/adrai/flowchart.js/blob/master/types/index.d.ts  
https://github.com/adrai/flowchart.js/pull/212

**Comment by adrai** [comment]
You're right... I forgot... too many open source projects 🤣
