### ISSUE TITLE
Could you add input, output type?

### ISSUE THREAD

**Issue by dstang2000** [adrai/flowchart.js#250]
Before coding in Python at the begining, kids are learning bases of programing logic together with drawing flowcharts and pseudo lanuage.
Probably by standard we are using there is some different symbols. It makes a bit small problem to understand the flowchart espetially for begginers. 
Example, we are using different symbol for input and output.

![image](https://github.com/adrai/flowchart.js/assets/8474293/dc3b52f1-827f-4ce0-b6b2-3ccf0f2d7570)
Data output:
![image](https://github.com/adrai/flowchart.js/assets/8474293/526e0b9f-52fd-4a5b-ba42-2f759703612d)
Data input:

![image](https://github.com/adrai/flowchart.js/assets/8474293/058ef4af-5648-4293-9ce4-f7e7400c0a35)

And I  copy **inputoutput.js to input.js and output.js**, and change their shapes, could I make a PR?

**Comment by adrai** [comment]
released with v1.18.0
