### ISSUE TITLE
ESM install issue: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by jsimonrichard** [adrai/flowchart.js#254]
I just installed flowchart.js 1.18.0. However, when I run `tsc` I get the following:
```
node_modules/flowchart.js/types/index.d.ts:42:3 - error TS2309: An export assignment cannot be used in a module with other exported elements.

42   export = FlowChart;
     ~~~~~~~~~~~~~~~~~~~
```

My `tsconfig.json` is:
```json
{
  "compilerOptions": {
    "module": "es2020",
    "target": "es2017",
    "lib": [
      "es2020",
      "dom"
    ],
    "declaration": true,
    "outDir": ".",
    "baseUrl": ".",
    "moduleResolution": "node",
    "paths": {
      "*": [
        "node_modules/*"
      ]
    },
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

This is the project I'm working on: https://github.com/jsimonrichard/HyperMD/tree/dev (commit: https://github.com/jsimonrichard/HyperMD/commit/2826ea44facf7cbccc36a705b63d25d5caab1ef8). I tried but was unable to create a minimal reproduction repo.

My current workaround is to set `"skipLibCheck"` to `true`.

This error has popped up on a number of other repositories/projects:
* https://github.com/puppeteer/puppeteer/issues/6852 (fix: https://github.com/stencila/encoda/commit/0ca62bdfc31f0b367e9c6bcfa93e621f6707fcf0)
* https://stackoverflow.com/questions/55701403/export-assignment-cannot-be-used-when-targeting-ecmascript-modules
* https://github.com/telegraf/telegraf/issues/1491

It looks like you've already implemented https://stackoverflow.com/questions/48708410/typescript-error-an-export-assignment-cannot-be-used-in-a-module-with-other-exp, but for whatever reason it's not working with my setup.

It seems to me that switching to `export default` in `types/index.d.ts` might do the trick, but you know your repo better than I do.

**Comment by adrai** [comment]
//cc @Mister-Hope

**Comment by Mister-Hope** [comment]
I believed my declaration file is correct. And i am really busy in my real life now.  So it would be great if you can figure out more details by your own and try to provide a minimal reproduction

**Comment by jsimonrichard** [comment]
Thanks for the response!

This issue isn't blocking for me yet (the library I'm building should support flowchart.js or something like it someday, but it doesn't have to right now) and I'm also super busy. I will revisit this if and when necessary (with a minimal reproduction).

**Comment by ghiscoding** [comment]
hey guys, I came across this issue while I was researching for the same TypeScript build error for similar usage in the newest version of DOMPurify. I found that the easiest way to fix it was to simply add `// @ts-ignore` on top of the `export = ...` as shown in this DOMPurify [PR](https://github.com/cure53/DOMPurify/pull/1022). 

Cheers
