### ISSUE TITLE
individual line length modification

### ISSUE THREAD

**Issue by oskude** [adrai/flowchart.js#33]
so i'm pretty happy how this flowchart looks:

![minirfc821flow](https://cloud.githubusercontent.com/assets/157669/4175264/e8f60f90-35c9-11e4-92bf-5654b9546a4d.png)
(_click to see in original size_)

but it's really itching me to modify the following:
- first line segment after `/ 250 Ok. /` should be shorter
- first line segment after `/ 250 Done. /` should be longer
- line after `< ^DATA > no` should be shorter

i naively thought that if we could just inject modification values from the flowchart syntax - _cause "fixing" the whole auto layout algorithm probably would never work for every chart_ -, we then would only need to add this modification value to the line length in code... well, i got the first part done:

``` diff
diff --git a/release/flowchart-1.3.4.js b/release/flowchart-1.3.4.js
index fe6051a..b76c816 100644
--- a/release/flowchart-1.3.4.js
+++ b/release/flowchart-1.3.4.js
@@ -446,6 +446,7 @@
     this.symbol = symbol;
     this.connectedTo = [];
     this.symbolType = options.symbolType;
+    this.lineLengthMod = options.lineLengthMod;
     this.flowstate = (options.flowstate || 'future');

     this.next_direction = options.next && options['direction_next'] ? options['direction_next'] : undefined;
@@ -1381,14 +1382,17 @@

         chart.symbols[symbol.key] = symbol;

-      } else if (line.indexOf('->') >= 0) {
+      } else if (/-[\{-\d\}]*>/.test(line)) {
         // flow
-        var flowSymbols = line.split('->');
-        for (var i = 0, lenS = flowSymbols.length; i < lenS; i++) {
-          var flowSymb = flowSymbols[i];
+        var flowSymbols = line.split(/-[\{]*([-\d]*)[\}]*>/);
+
+        for (var j = 0, lenS = flowSymbols.length; j < lenS; j+=2) {
+          var i = j/2;
+          var flowSymb = flowSymbols[j];

           var realSymb = getSymbol(flowSymb);
           var next = getNextPath(flowSymb);
+          realSymb.lineLengthMod = parseInt(flowSymbols[j+1], 10) || 0;

           var direction = null;
           if (next.indexOf(',') >= 0) {
@@ -1401,8 +1405,8 @@
             chart.start = realSymb;
           }

-          if (i + 1 < lenS) {
-            var nextSymb = flowSymbols[i + 1];
+          if (j + 2 < lenS) {
+            var nextSymb = flowSymbols[j + 2];
             realSymb[next] = getSymbol(nextSymb);
             realSymb['direction_' + next] = direction;
             direction = null;
```

that allows to do:

```
foo->bar-{10}>zap-{-20}>fop
```

and in (javascript) code we have for the `bar` object `lineLengthMod:10` and for `zap` object `lineLengthMod:-20` attributes.

for the second part i just could not findout where to modify the (first) line (segment) lengths in the spots i wanted to, so i'm giving up for now and hope someone else can figure it out. :heart_eyes:

ps. source for the image can be found at http://ix.io/edM

**Comment by oskude** [comment]
sorry for late reply!
closing cause _i-forgot-and-now-doing-other-things_ :sweat_smile:

**Comment by jiexishede** [comment]
Can the latest version of flowchart.js modify the individual line length?

**Comment by adrai** [comment]
No

**Comment by jiexishede** [comment]
My English is poor.  I can't show you my disappointment to know this message.
