### ISSUE TITLE
Chart not rendering properly when code loaded via AJAX

### ISSUE THREAD

**Issue by erdalkaraca** [adrai/flowchart.js#45]
I am getting the chart's code via JQuery's get() to load. Unfortunately, the flowchart does not render properly.
The JS code looks like this:

""""
$(document).ready(function() {
    var url = "sample.txt";
    $.ajax({
        url : url,
        dataType : "text",
        success : function(data) {
            var chart = flowchart.parse(data);
            chart.drawSVG('canvas');
        }
    });
});
""""

The sample.txt contents looks like this:

""""
st=>start: Start:>http://www.google.com[blank]
e=>end:>http://www.google.com
op1=>operation: My Ooooperation
sub1=>subroutine: My Subroutine
cond=>condition: Yes 
or No?:>http://www.google.com
io=>inputoutput: catch something...

st->op1->cond
cond(yes)->io->e
cond(no)->sub1(right)->op1
""""

I can see st and op1 being rendered but the rest is missing.
There are no console errors logged and the parse() function evaluates without any errors.
Do you have any hints what to check?

Thanks.

**Comment by adrai** [comment]
can you do a sample in this directory? https://github.com/adrai/flowchart.js/tree/master/example
just create a pull request...

**Comment by erdalkaraca** [comment]
I have modified the index.html file. Did a pull request.
Thanks.

**Comment by adrai** [comment]
ok I added your files: https://github.com/adrai/flowchart.js/tree/master/example
I tested on my mac book in chrome and safari, and it works as expected...

**Comment by Timoses** [comment]
Experienced the same issue. Could be browser related as well.

For me it was an error that when taking a line from the lines array the last entry had a space in the end. This lead to an undefined flowSymbol and therefore probably an undefined next object (therefore the cut-off after op1).

Pull request:
https://github.com/adrai/flowchart.js/pull/105

**Comment by adrai** [comment]
try v1.6.6

**Comment by Timoses** [comment]
Works! 👍 

Issue can be closed I'd guess.
