### ISSUE TITLE
Not rendering complete flowchart when code is a bit longer.

### ISSUE THREAD

**Issue by legendxcheng** [adrai/flowchart.js#48]
st=>start: Start
p1=>operation: DFA gets action
p2=>operation: DFA changes state
p3=>operation: DFA stops
p4=>operation: Send action to server
p5=>operation: Save robot data
p6=>operation: Set this action unavailable
cond1=>condition: Has action?
cond2=>condition: DFA can stop?
cond3=>condition: Action succ?
e=>end

st->p1->cond1
cond1(yes)->p4
cond1(no)->p2
p2(right)->p1
p4->cond3
cond3(no)->p1
cond3(yes,bottom)->p6
p6(right)->p1
cond2(no)->p1
cond2(yes)->p5
p5->e

you can try code above.

**Comment by ducva** [comment]
I don't see the connection to cond2 node. I think that is the root cause.

**Comment by adrai** [comment]
I can confirm: no connection to cond2

**Comment by legendxcheng** [comment]
yep, I'm so careless!
Sorry for opening this issue.
