### ISSUE TITLE
Allow storing the flowchart data/code inside a div element.

### ISSUE THREAD

**Issue by bwmarrin** [adrai/flowchart.js#54]
It would be nice to store the text that flowchart parses within a div element. Then, you could just pull the innerHTML contents of that div to parse.  It would make using this library much easier.  I've tried to do this by pulling the contents of a div and passing that to flowchart but it complains

```
Uncaught TypeError: Cannot read property 'key' of null  (Line 1205 flowchart.js)
```

I believe this is because the innerHTML doesn't actually have \n line breaks.  Do you know of an easy way to implement this or could flowchart.js not require the line breaks?  Maybe have an alternate method to break lines such as a semicolon?

**Comment by bwmarrin** [comment]
Looking close at the js-sequence-diagram project I've found a way to implement this request using the same jQuery method that project follows.

To accomplish this, you will need to include the below jQuery plugin code
```
if (typeof jQuery != 'undefined') {
	(function( $ ) {
		$.fn.flowchart = function( options ) {
			return this.each(function() {
				var $this = $(this);
				var diagram = flowchart.parse($this.text());
				$this.html('');
				diagram.drawSVG(this, options);
			});
		};
	})( jQuery );
}
```

Once that is done, you can access flowchart.js the following way.  In the below example I am including a file jquery-plugin.js which only just contains the above snippit.



```
<div class="diagram">
st=>start: Start|past:>http://www.google.com[blank]
e=>end: Ende|future:>http://www.google.com
op1=>operation: My Operation|past
op2=>operation: Stuff|current
sub1=>subroutine: My Subroutine|invalid
cond=>condition: Yes 
or No?|approved:>http://www.google.com
c2=>condition: Good idea|rejected
io=>inputoutput: catch something...|future

st->op1(right)->cond
cond(yes, right)->c2
cond(no)->sub1(left)->op1
c2(yes)->io->e
c2(no)->op2->e
</div>

<script src="jquery-2.1.1.min.js"></script>
<script src="raphael-min.js"></script>
<script src="flowchart-1.4.0.js"></script>
<script src="jquery-plugin.js"></script>

<script>
$(".diagram").flowchart({theme: 'simple'});
</script>
```

**Comment by bwmarrin** [comment]
Usage example and code are now provided in the MkDocs+ Project

https://github.com/bwmarrin/MkDocsPlus

**Comment by adrai** [comment]
nice ;-)

**Comment by dvdcastro** [comment]
@bwmarrin Take a look at #56

**Comment by bwmarrin** [comment]
FYI.  I've updated my MkDocsPlus example for flowchart.js using the latest version.  The jquery plugin "mod" is still working great to allow you to embed the graph data right inside the html file.  You're welcome to include that into your own code @adrai if you'd like.

http://bwmarrin.github.io/MkDocsPlus/flowchartjs/

I'm going to close this issue however since it seems silly to leave it open forever :)
