### ISSUE TITLE
remove the version number

### ISSUE THREAD

**Issue by maruilian11** [adrai/flowchart.js#58]
could you consider removing the version number of `release` folder, just difference each version by tags so that we can add your lib on https://cdnjs.com **with git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5056

**Comment by adrai** [comment]
Will do it next week... I'm afk

**Comment by adrai** [comment]
done

**Comment by maruilian11** [comment]
thank you very much!
