### ISSUE TITLE
use SVG.js instead of Raphael

### ISSUE THREAD

**Issue by ctzurcanu** [adrai/flowchart.js#62]
First: congrats on this project!

Raphael is quite long and not intuitive. A better choice would be SVG.js 
http://documentup.com/wout/svg.js

I also made an adapter for Raphael->SVG.js for this project and the output is encouraging - not perfect
changes:

```
<script src="raphaela.js"></script>
<script src="svg.js"></script>
<script src="flowchart.js"></script
```

and raphaela.js (Raphael adaptor)
```
var Raphael = function(container, options){
	this.paper = SVG(container)
	this.registerFont = function(font){
	//
	return;
}
}

Raphael.prototype.text = function(x, y, text){
	console.log(x,y)
	var text= this.paper.text(text)
	//text.move(x,-text.height)
	text.getBBox= function(){
		return this.tbox()
	}
	return text
}

Raphael.prototype.rect = function(x, y, width, height, round){
	var rect = this.paper.rect(width, height)//.move(x,y-10)
	if (round) rect.radius(round)
	rect.insertBefore = function(obj){
		this.parent().add(obj)
		this.back()
	}
	rect.getBBox= function(){
		return this.tbox()
	}
	return rect
}

Raphael.prototype.set = function(){
	var gr = this.paper.group()
	gr.getBBox= function(){
		var box = this.tbox()
		return box
	}
	gr.push = function(obj){
		this.add(obj)
	}
	gr.transforma =function(trans){
		trans = trans.substring(1)
		var coords = trans.split(",")
		this.move(parseInt(coords[0]),parseInt(coords[1]))
	}
	return gr
}

Raphael.prototype.path = function(path,pathValues){
	console.log(path)
	console.log(pathValues)
	for (ndx in pathValues){
		var str = "{"+ndx+"}"
		path = path.replace(str,pathValues[ndx])
	}
	console.log(path)
	var rect = this.paper.path(path).fill("none")//.move(0,-10)
	rect.insertBefore = function(obj){
		this.parent().add(obj)
		this.backward()
	}
	rect.getBBox= function(){
		return this.tbox()
	}
	return rect
}

Raphael.prototype.setSize = function(width, height){
	this.paper.size(width,height)
}

Raphael.prototype.setViewBox = function(x, y, w, h, fit){
	this.paper.viewbox(x, y, w, h)  // , fit
}
```

I would have attached the output, but is too long. please pm me if you are unable to see it from these instructions.

One more thing: "transform" has to be written as "transforma" in flowchart.js because it interferes with SVG.js and has to be treated by raphaela.

**Comment by adrai** [comment]
interesting...
it would be nice to support both Raphael and SVG (via raphaela)
Can you try to do a PR?

**Comment by ctzurcanu** [comment]
Yes.. I forgot to mention: 'path' is not a SVG-compatible attribute. changed it to 'd'. You got the PR
I would like to help here. Tell me how. At least I can do testing.

**Comment by ctzurcanu** [comment]
almost done in the raphaela branch of this project

**Comment by ctzurcanu** [comment]
another useful hack in the present situation, but related to the Raphael side: add a new function with Raphael.fn.transforma that will simply do a Raphael.transform. This way all the present code in the raphaela branch will work both with svg.js and raphael without changes.
Then you may want to do what you proposed with small code differentiation with if (Raphael.type() == "SVG" or "svg.js") for raphael or raphaela.
