### ISSUE TITLE
bottom line was missing

### ISSUE THREAD

**Issue by bozzom** [adrai/flowchart.js#67]
Hi, I put my code whtin http://adrai.github.io/flowchart.js/ dome1
the bottom condition block should have connected to the middle vertical line, but it's not.

``` 
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
top=>operation: My Operation
tcond=>condition: Continue or Not?
e=>end

st->op->cond
cond(yes)->top->tcond
cond(no)->e
tcond(yes)->op->cond
tcond(no)->e
```

**Comment by jackycute** [comment]
Hi, I was reported the same issue.
Actually it's connected but have been cut off.
like this:
<img width="359" alt="2016-01-26 10 03 41" src="https://cloud.githubusercontent.com/assets/2639151/12603560/6746e0d8-c479-11e5-86cf-4f8f652bd8cf.png">

I think this issue might be the viewBox size not calculate correctly.
I will look for it later.

**Comment by jackycute** [comment]
Made a workaround for this and also a pull request.
https://github.com/adrai/flowchart.js/pull/72

**Comment by adrai** [comment]
v1.6.1

**Comment by jackycute** [comment]
:+1: Thanks a lot!
