### ISSUE TITLE
Does flowchart.js has CLI mode? I would like to convert flowchart files to png files.

### ISSUE THREAD

**Issue by timesking** [adrai/flowchart.js#84]
Hi, 

I'm not familiar with javascript.
But I have a lot of markdown files use code block with flowcharts.js.
Right now, I would like to convert flowchart files to png files. and convert all my markdown files instead flowchart.js code block to png links.

Do you guys now how to make it happen?
Even any hint will be appriciated.

**Comment by formatc1702** [comment]
Hi,
I had the exact same question, and have found a tool that might help you.
https://github.com/francoislaberge/diagrams

**Comment by timesking** [comment]
It is really helpful. Thanks @formatc1702

**Comment by lackovic** [comment]
> Hi,
> I had a similar question (auto-generate SVG/PNG from a file), and have found a tool that might help you.
> https://github.com/francoislaberge/diagrams

That is a good option, but unfortunately it doesn't seem like it can generate PNGs, it only generates SVGs.
