### ISSUE TITLE
Flowchart.js github pages broken (ACE.js Dependency 404ing)

### ISSUE THREAD

**Issue by francoislaberge** [adrai/flowchart.js#92]
Hi. Looks like the website for this is broken. You currently can't use the code editors to preview what the SVG would look like. Seems at a quick glance in devtools that the ACE editor isn't accessible from your page anymore. Maybe something going on with the CDN.

**Comment by francoislaberge** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1845/19818640/a4c41ccc-9d1e-11e6-93ac-515dc8f29e5e.png)

**Comment by francoislaberge** [comment]
This was corroborated by a user of a downstream project I created here: https://github.com/francoislaberge/diagrams/issues/3, he was seeing the same issue.

**Comment by adrai** [comment]
Can you submit a PR to the gh-pages branch?

**Comment by adrai** [comment]
should be fixed now, thx
