### ISSUE TITLE
Documentation for how to write flowcharts

### ISSUE THREAD

**Issue by IanEdington** [adrai/flowchart.js#95]
Is there documentation somewhere on how to write these flowcharts?  
Is the language used unique to this package?  

It would be nice to either point to documentation or give a quick outline of the options. I would be willing to write something up, however, I would need more info on how it works first.

For example this seems to be an example of defining an object
st=>start: Start:>http://www.google.com[blank]
- `st=>start` seems to define an object "st" with the type "start"
    - What other types are there? (start, end, operation, subroutine, condition, inputoutput)
- `:` seems to add additional properties to the object
    - `: ` seems to name the object ie. `: Start` names the object "Start"
    - `:>http://www.google.com[blank]` seems to make an html link with optional `[blank]`

"start end operation" seem to be special structures. Are there others?
What options are available for naming lines?

**Comment by adrai** [comment]
everything you can use is in the examples there is nothing more...
flowchart.js.org

**Comment by WangYihang** [comment]
@adrai Hi, bro, thank you for your excellent work~ flowcharts.js is brilliant.
I have a little question, is there a document for the syntax of this tool?
just like this project: 

> https://mermaidjs.github.io/flowchart.html

It's a little confusing for a newbie to use it...
thanks a lot~

**Comment by adrai** [comment]
not right now

**Comment by WangYihang** [comment]
okay, well... thank you so much~
