### ISSUE TITLE
Would you like to upgrade engine parameter on package.json?

### ISSUE THREAD

**Issue by sota1235** [adrai/flowchart.js#98]
Hello, devs!!

flowchart.js is so cool, so I want to use this with using npm and bundle it with using the tool(For example, webpack).
But `package.json` specifies the version of node.js (The source is [here](https://github.com/adrai/flowchart.js/blob/master/package.json#L8)), I want to use version of node.js over v4~.

Can you upgrade the parameter of `engine`?

Thanks!!

**Comment by sota1235** [comment]
If there is no reason for this parameter, I will fix it and send pull request :)

**Comment by adrai** [comment]
v1.6.5 ;-)

**Comment by sota1235** [comment]
Thank you for fixing!
